# Generated by Django 5.0.6 on 2025-01-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_devicedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
