# Generated by Django 5.0.6 on 2025-02-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_otp_otp_otp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp_code',
            new_name='code',
        ),
    ]
